version: 1.0.{build}
os: Windows Server 2012 R2
configuration: Release
init:
	- ps: git config --global core.autocrlf true
environment:
  COVERALLS_REPO_TOKEN:
    secure: o8b2zjTYPnMUPBdCzXAvZZnAEkRvLdGE7MNTDOC5R/JURTxu/JcAprXPyOkOPtdx
install:
	- choco install resharper-clt -y
	- choco install opencover -source https://nuget.org/api/v2/
	- choco install coveralls.io -source https://nuget.org/api/v2/
	- choco install nvika -y
nuget:
  project_feed: true
before_build:
- nuget restore
build:
  project: GitCITestRepo.sln
  verbosity: minimal
after_build:
	- inspectcode /o="inspectcodereport.xml" /project="GitCITestRepo" "GitCITestRepo.sln"
	- NVika parsereport "inspectcodereport.xml" --debug --includesource
test_script:
	- ps: OpenCover.Console.exe -register:user -target:nunit-console.exe "-targetargs:"".\GitCITestRepo.Tests\bin\$env:CONFIGURATION\GitCITestRepo.Tests.dll"" /noshadow" -filter:"+[GitCITestRepo*]*" -output:coverage.xml
	- ps: coveralls.net --opencover coverage.xml --full-sources
artifacts:
- path: inspectcodereport.xml
- path: testresults.xml
- path: coverage.xml
- path: $(APPVEYOR_PROJECT_NAME)\bin\$(configuration)
  name: $(APPVEYOR_PROJECT_NAME)